// ============================================================
// SINBORN ODYSSEY 2 - Scroll Chest Loot Injection (V7 RARITY REBUILD 2026-06-07)
//
// RARITY = QUESTBOOK CHAPTER. A discipline's tier follows the chapter that gates
// it, so rarity tracks progression: early chapters common, endgame rare.
//   Ch1-3 -> T1 (35%)   Ch4-5 -> T2 (25%)   Ch6-8 -> T3 (17%)
//   Ch9-11 -> T4 (11%)  Ch12-14 -> T5 (7%)  Ch15-17 -> T6 (4%)
// Overrides: magic schools >= T3 (earned); god/vessel lore = T6 (legendary);
//   survival floor = T1 (always findable). blood_and_oil = quest-only (no drop).
// Thematic chest placement preserved from V6; only weights rebuilt + dead markers purged.
//
// Droppable disciplines: 165   Total entries: 1003   (updated 2026-06-15 post-remap)
// ============================================================

var SCROLL_SOURCES = [
  // -- spoils_of_the_sea_roads (Tidehold, found at sea) --
  ['spoils_of_the_sea_roads', 'minecraft:chests/shipwreck_supply', 17],
  ['spoils_of_the_sea_roads', 'minecraft:chests/shipwreck_treasure', 17],
  ['spoils_of_the_sea_roads', 'minecraft:chests/underwater_ruin_big', 17],
  ['spoils_of_the_sea_roads', 'minecraft:chests/underwater_ruin_small', 17],
  ['spoils_of_the_sea_roads', 'minecraft:chests/buried_treasure', 17],
  ['spoils_of_the_sea_roads', 'aquamirae:chests/frozen_chest', 17],
  // -- broad_foods (broad cookery / baseline) --
  ['broad_foods', 'minecraft:chests/village/village_plains_house', 35],
  ['broad_foods', 'minecraft:chests/village/village_savanna_house', 35],
  ['broad_foods', 'minecraft:chests/village/village_butcher', 35],
  ['broad_foods', 'farmersdelight:chests/fd_village_plains_house', 35],
  ['broad_foods', 'minecraft:chests/village/village_taiga_house', 35],
  // -- common_hearth (broad cookery / baseline) --
  ['common_hearth', 'minecraft:chests/village/village_desert_house', 35],
  ['common_hearth', 'minecraft:chests/village/village_snowy_house', 35],
  ['common_hearth', 'minecraft:chests/village/village_mason', 35],
  ['common_hearth', 'minecraft:chests/miners_home', 35],
  ['common_hearth', 'minecraft:chests/village/village_fletcher', 35],
  // -- forgetting_broth (Cipher cave cuisine, found in caves) --
  ['forgetting_broth', 'minecraft:chests/abandoned_mineshaft', 17],
  ['forgetting_broth', 'minecraft:chests/simple_dungeon', 17],
  ['forgetting_broth', 'minecraft:chests/mineral', 17],
  ['forgetting_broth', 'minecraft:chests/stone', 17],
  ['forgetting_broth', 'miners_delight:chests/md_abandoned_mineshaft', 17],
  ['forgetting_broth', 'minecraft:chests/miners_home', 17],
  // -- resonant_larder (food culture) --
  ['resonant_larder', 'minecraft:chests/ancient_city', 11],
  ['resonant_larder', 'minecraft:chests/ancient_city_ice_box', 11],
  ['resonant_larder', 'minecraft:chests/abandoned_mineshaft', 11],
  // -- quarry_table (food culture) --
  ['quarry_table', 'minecraft:chests/simple_dungeon', 25],
  ['quarry_table', 'minecraft:chests/abandoned_mineshaft', 25],
  ['quarry_table', 'dungeonsdelight:chests/rotten_dungeon', 25],
  ['quarry_table', 'minecraft:chests/woodland_mansion', 25],
  // -- festival_board (food culture) --
  ['festival_board', 'minecraft:chests/village/village_plains_house', 25],
  ['festival_board', 'minecraft:chests/village/village_desert_house', 25],
  ['festival_board', 'minecraft:chests/village/village_savanna_house', 25],
  // -- brimstone_larder (Nether cuisine, found in the Nether) --
  ['brimstone_larder', 'minecraft:chests/nether_bridge', 17],
  ['brimstone_larder', 'minecraft:chests/bastion_treasure', 17],
  ['brimstone_larder', 'netherexp:chests/sanctum_food', 17],
  ['brimstone_larder', 'netherexp:chests/sanctum_supply', 17],
  ['brimstone_larder', 'nethervinery:chests/bastion_other', 17],
  ['brimstone_larder', 'mynethersdelight:chests/mnd_bastion_treasure', 17],
  // -- abyssal_chasm --
  ['abyssal_chasm', 'aquamirae:chests/frozen_chest', 17],
  ['abyssal_chasm', 'minecraft:chests/shipwreck_map', 17],
  ['abyssal_chasm', 'minecraft:chests/shipwreck_supply', 17],
  ['abyssal_chasm', 'minecraft:chests/shipwreck_treasure', 17],
  ['abyssal_chasm', 'minecraft:chests/underwater_ruin_big', 17],
  ['abyssal_chasm', 'minecraft:chests/underwater_ruin_small', 17],
  // -- aeronautics --
  ['aeronautics', 'ati_structures:chests/coal_storage', 16],
  ['aeronautics', 'ati_structures:chests/construction', 16],
  ['aeronautics', 'ati_structures:chests/copper_storage', 16],
  ['aeronautics', 'ati_structures:chests/food_storage', 16],
  ['aeronautics', 'minecraft:chests/rich_cart', 16],
  ['aeronautics', 'minecraft:chests/village/village_cartographer', 16],
  // -- agronomic_path --
  ['agronomic_path', 'minecraft:chests/miners_home', 35],
  ['agronomic_path', 'minecraft:chests/village/village_armorer', 35],
  ['agronomic_path', 'minecraft:chests/village/village_fletcher', 35],
  ['agronomic_path', 'minecraft:chests/village/village_mason', 35],
  ['agronomic_path', 'minecraft:chests/village/village_plains_house', 35],
  ['agronomic_path', 'minecraft:chests/village/village_savanna_house', 35],
  // -- alchemy --
  ['alchemy', 'ati_structures:chests/library', 14],
  ['alchemy', 'ctov:chests/village/village_library', 14],
  ['alchemy', 'exposure:chests/stronghold_crossing', 14],
  ['alchemy', 'minecraft:chests/stronghold_corridor', 14],
  ['alchemy', 'minecraft:chests/stronghold_crossing', 14],
  ['alchemy', 'minecraft:chests/stronghold_library', 14],
  // -- apothecarys_tonic --
  ['apothecarys_tonic', 'alexscaves:chests/abyssal_ruins', 25],
  ['apothecarys_tonic', 'alexscaves:chests/caveman_house', 25],
  ['apothecarys_tonic', 'alexscaves:chests/forlorn_ruins', 25],
  ['apothecarys_tonic', 'minecraft:chests/ancient_city', 25],
  ['apothecarys_tonic', 'minecraft:chests/ancient_city_ice_box', 25],
  ['apothecarys_tonic', 'minecraft:chests/ruined_library', 25],
  // -- arcane_codex --
  ['arcane_codex', 'ati_structures:chests/library', 17],
  ['arcane_codex', 'ctov:chests/village/village_library', 17],
  ['arcane_codex', 'exposure:chests/stronghold_crossing', 17],
  ['arcane_codex', 'ice_and_fire_spellbooks:chests/fodaan_mask', 17],
  ['arcane_codex', 'ice_and_fire_spellbooks:chests/toornahkriin_mask', 17],
  ['arcane_codex', 'ice_and_fire_spellbooks:chests/vulnilviir_mask', 17],
  // -- archaeology_mastery --
  ['archaeology_mastery', 'minecraft:chests/abandoned_mineshaft', 35],
  ['archaeology_mastery', 'minecraft:chests/dye', 35],
  ['archaeology_mastery', 'minecraft:chests/mineral', 35],
  ['archaeology_mastery', 'minecraft:chests/miners_ruined_shack', 35],
  ['archaeology_mastery', 'minecraft:chests/stone', 35],
  ['archaeology_mastery', 'minecraft:chests/trial_chambers/supply', 35],
  // -- architects_codex --
  ['architects_codex', 'ati_structures:chests/construction', 25],
  ['architects_codex', 'ati_structures:chests/stone_storage', 25],
  ['architects_codex', 'exposure:chests/stronghold_crossing', 25],
  ['architects_codex', 'integrated_stronghold:chests/bedroom', 25],
  ['architects_codex', 'integrated_stronghold:chests/brewing', 25],
  ['architects_codex', 'integrated_stronghold:chests/crypt', 25],
  ['architects_codex', 'integrated_stronghold:chests/dining_hall', 25],
  // -- architectural_mastery --
  ['architectural_mastery', 'ati_structures:chests/construction', 25],
  ['architectural_mastery', 'ati_structures:chests/stone_storage', 25],
  ['architectural_mastery', 'exposure:chests/stronghold_crossing', 25],
  ['architectural_mastery', 'integrated_stronghold:chests/bedroom', 25],
  ['architectural_mastery', 'integrated_stronghold:chests/brewing', 25],
  ['architectural_mastery', 'integrated_stronghold:chests/crypt', 25],
  ['architectural_mastery', 'integrated_stronghold:chests/dining_hall', 25],
  // -- arsenal_iron_blades --
  ['arsenal_iron_blades', 'abridged:chests/pillager_bridge', 35],
  ['arsenal_iron_blades', 'ati_structures:chests/archer_chest', 35],
  ['arsenal_iron_blades', 'ati_structures:chests/archer_chest2', 35],
  ['arsenal_iron_blades', 'minecraft:chests/pillager_outpost', 35],
  ['arsenal_iron_blades', 'minecraft:chests/simple_dungeon', 35],
  ['arsenal_iron_blades', 'minecraft:chests/woodland_mansion', 35],
  // -- arsenal_iron_polearms --
  ['arsenal_iron_polearms', 'abridged:chests/pillager_bridge', 35],
  ['arsenal_iron_polearms', 'ati_structures:chests/archer_chest', 35],
  ['arsenal_iron_polearms', 'ati_structures:chests/archer_chest2', 35],
  ['arsenal_iron_polearms', 'ati_structures:chests/armory', 35],
  ['arsenal_iron_polearms', 'beachparty:chests/simple_dungeon', 35],
  ['arsenal_iron_polearms', 'beachparty:chests/woodland_mansion', 35],
  // -- arsenal_iron_ranged --
  ['arsenal_iron_ranged', 'ati_structures:chests/armory', 14],
  ['arsenal_iron_ranged', 'beachparty:chests/simple_dungeon', 14],
  ['arsenal_iron_ranged', 'beachparty:chests/woodland_mansion', 14],
  ['arsenal_iron_ranged', 'celestisynth:chests/underground_dungeons', 14],
  ['arsenal_iron_ranged', 'chalk:chests/simple_dungeon_chalk_loot', 14],
  ['arsenal_iron_ranged', 'dungeonnowloading:chests/labyrinth/arrows', 14],
  // -- arsenal_legendary_blades --
  ['arsenal_legendary_blades', 'celestisynth:chests/underground_dungeons', 7],
  ['arsenal_legendary_blades', 'chalk:chests/simple_dungeon_chalk_loot', 7],
  ['arsenal_legendary_blades', 'dungeonnowloading:chests/labyrinth/arrows', 7],
  ['arsenal_legendary_blades', 'dungeonnowloading:chests/labyrinth/enchantments/gigantism', 7],
  ['arsenal_legendary_blades', 'dungeonnowloading:chests/labyrinth/enchantments/overworked', 7],
  ['arsenal_legendary_blades', 'dungeonnowloading:chests/labyrinth/enchantments/pack_blessing', 7],
  // -- arsenal_legendary_polearms --
  ['arsenal_legendary_polearms', 'dungeonnowloading:chests/labyrinth/enchantments/gigantism', 7],
  ['arsenal_legendary_polearms', 'dungeonnowloading:chests/labyrinth/enchantments/overworked', 7],
  ['arsenal_legendary_polearms', 'dungeonnowloading:chests/labyrinth/enchantments/pack_blessing', 7],
  ['arsenal_legendary_polearms', 'dungeonnowloading:chests/labyrinth/enchantments/random', 7],
  ['arsenal_legendary_polearms', 'dungeonnowloading:chests/labyrinth/enchantments/reckless', 7],
  ['arsenal_legendary_polearms', 'dungeonnowloading:chests/labyrinth/enchantments/sacrifice', 7],
  // -- arsenal_legendary_ranged --
  ['arsenal_legendary_ranged', 'dungeonnowloading:chests/labyrinth/enchantments/random', 7],
  ['arsenal_legendary_ranged', 'dungeonnowloading:chests/labyrinth/enchantments/reckless', 7],
  ['arsenal_legendary_ranged', 'dungeonnowloading:chests/labyrinth/enchantments/sacrifice', 7],
  ['arsenal_legendary_ranged', 'dungeonnowloading:chests/labyrinth/flame_bow', 7],
  ['arsenal_legendary_ranged', 'dungeonnowloading:chests/labyrinth/foods', 7],
  ['arsenal_legendary_ranged', 'dungeonnowloading:chests/labyrinth/horse_gears', 7],
  // -- arsenal_master_blades --
  ['arsenal_master_blades', 'dungeonnowloading:chests/labyrinth/flame_bow', 12],
  ['arsenal_master_blades', 'dungeonnowloading:chests/labyrinth/foods', 12],
  ['arsenal_master_blades', 'dungeonnowloading:chests/labyrinth/horse_gears', 12],
  ['arsenal_master_blades', 'dungeonnowloading:chests/labyrinth/potion_bow', 12],
  ['arsenal_master_blades', 'dungeonnowloading:chests/labyrinth/reward', 12],
  ['arsenal_master_blades', 'dungeonnowloading:chests/labyrinth/rewards/enchantment_books', 12],
  // -- arsenal_master_polearms --
  ['arsenal_master_polearms', 'dungeonnowloading:chests/labyrinth/potion_bow', 17],
  ['arsenal_master_polearms', 'dungeonnowloading:chests/labyrinth/reward', 17],
  ['arsenal_master_polearms', 'dungeonnowloading:chests/labyrinth/rewards/enchantment_books', 17],
  ['arsenal_master_polearms', 'dungeonnowloading:chests/labyrinth/rewards/gears', 17],
  ['arsenal_master_polearms', 'dungeonnowloading:chests/labyrinth/rewards/materials', 17],
  ['arsenal_master_polearms', 'dungeonnowloading:chests/labyrinth/rewards/music_discs', 17],
  // -- arsenal_master_ranged --
  ['arsenal_master_ranged', 'dungeonnowloading:chests/labyrinth/rewards/gears', 17],
  ['arsenal_master_ranged', 'dungeonnowloading:chests/labyrinth/rewards/materials', 17],
  ['arsenal_master_ranged', 'dungeonnowloading:chests/labyrinth/rewards/music_discs', 17],
  ['arsenal_master_ranged', 'dungeonnowloading:chests/labyrinth/rewards/potions', 17],
  ['arsenal_master_ranged', 'dungeonnowloading:chests/labyrinth/suspicious_stew', 17],
  ['arsenal_master_ranged', 'dungeonnowloading:chests/labyrinth/woods', 17],
  // -- atomic_engineering --
  ['atomic_engineering', 'alexscaves:chests/toxic_ruins', 17],
  ['atomic_engineering', 'alexscaves:chests/underground_cabin_toxic_caves', 17],
  ['atomic_engineering', 'alexscaves:entities/nucleeper', 17],
  ['atomic_engineering', 'ati_structures:chests/coal_storage', 17],
  ['atomic_engineering', 'ati_structures:chests/construction', 17],
  ['atomic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 17],
  ['atomic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 17],
  ['atomic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 17],
  ['atomic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_tower', 17],
  ['atomic_engineering', 'traveloptics:chests/toxic_ruins_additions_new', 17],
  // -- backpackcraft --
  ['backpackcraft', 'ati_structures:chests/ingredients', 35],
  ['backpackcraft', 'burnt:chest_loot', 35],
  ['backpackcraft', 'minecraft:chests/miners_ruined_shack', 35],
  ['backpackcraft', 'minecraft:chests/stone', 35],
  ['backpackcraft', 'minecraft:chests/trial_chambers/supply', 35],
  ['backpackcraft', 'minecraft:chests/wood', 35],
  // -- ballistics_engineering --
  ['ballistics_engineering', 'ati_structures:chests/construction', 17],
  ['ballistics_engineering', 'ati_structures:chests/copper_storage', 17],
  ['ballistics_engineering', 'ati_structures:chests/food_storage', 17],
  ['ballistics_engineering', 'ati_structures:chests/gold_storage', 17],
  ['ballistics_engineering', 'ati_structures:chests/iron_storage', 17],
  ['ballistics_engineering', 'ati_structures:chests/minerals', 17],
  // -- banner_heraldry --
  ['banner_heraldry', 'dungeonnowloading:chests/labyrinth/rewards/potions', 12],
  ['banner_heraldry', 'dungeonnowloading:chests/labyrinth/suspicious_stew', 12],
  ['banner_heraldry', 'dungeonnowloading:chests/labyrinth/woods', 12],
  ['banner_heraldry', 'dungeonnowloading:chests/temple_of_duality/armor/easy_combat', 12],
  ['banner_heraldry', 'dungeonnowloading:chests/temple_of_duality/armor/easy_puzzle', 12],
  ['banner_heraldry', 'dungeonnowloading:chests/temple_of_duality/armor/hard_combat', 12],
  // -- beehive_logistics --
  ['beehive_logistics', 'ctov:chests/village/village_farm', 17],
  ['beehive_logistics', 'ctov:chests/village/village_forager', 17],
  ['beehive_logistics', 'minecraft:chests/village/village_butcher', 17],
  ['beehive_logistics', 'minecraft:chests/village/village_fisher', 17],
  ['beehive_logistics', 'minecraft:chests/village/village_shepherd', 17],
  ['beehive_logistics', 'minecraft:chests/village/village_tannery', 17],
  // -- bestiary_alex_mobs --
  ['bestiary_alex_mobs', 'ctov:chests/village/village_farm', 17],
  ['bestiary_alex_mobs', 'ctov:chests/village/village_forager', 17],
  ['bestiary_alex_mobs', 'ctov:chests/village/village_mushroom_house', 17],
  ['bestiary_alex_mobs', 'farmersdelight:chests/fd_village_butcher', 17],
  ['bestiary_alex_mobs', 'irons_spellbooks:chests/mangrove_hut', 17],
  ['bestiary_alex_mobs', 'minecraft:chests/village/village_tannery', 17],
  // -- blighted_hollows --
  ['blighted_hollows', 'minecraft:chests/bastion_bridge', 17],
  ['blighted_hollows', 'minecraft:chests/bastion_hoglin_stable', 17],
  ['blighted_hollows', 'minecraft:chests/bastion_other', 17],
  ['blighted_hollows', 'minecraft:chests/bastion_treasure', 17],
  ['blighted_hollows', 'minecraft:chests/nether_bridge', 17],
  ['blighted_hollows', 'minecraft:chests/nether_totemloot', 17],
  // -- blood_and_oil --
  ['blood_and_oil', 'ati_structures:chests/gold_storage', 18],
  ['blood_and_oil', 'ati_structures:chests/iron_storage', 18],
  ['blood_and_oil', 'ati_structures:chests/minerals', 18],
  ['blood_and_oil', 'ati_structures:chests/potion_storage', 18],
  ['blood_and_oil', 'ati_structures:chests/stone_storage', 18],
  ['blood_and_oil', 'ati_structures:chests/wood_storage', 18],
  // create_ltab Oil Rig (deep-ocean water tier) , the oil structure
  ['blood_and_oil', 'create_ltab:water/basic_loot', 18],
  // -- blood_school --
  ['blood_school', 'ice_and_fire_spellbooks:chests/fodaan_mask', 17],
  ['blood_school', 'ice_and_fire_spellbooks:chests/toornahkriin_mask', 17],
  ['blood_school', 'ice_and_fire_spellbooks:chests/vulnilviir_mask', 17],
  ['blood_school', 'ice_and_fire_spellbooks:chests/vulonqo_mask', 17],
  ['blood_school', 'ice_and_fire_spellbooks:chests/vulsilah_mask', 17],
  ['blood_school', 'integrated_stronghold:chests/brewing', 17],
  // -- bookshelf_mastery --
  ['bookshelf_mastery', 'ice_and_fire_spellbooks:chests/vulonqo_mask', 25],
  ['bookshelf_mastery', 'ice_and_fire_spellbooks:chests/vulsilah_mask', 25],
  ['bookshelf_mastery', 'integrated_stronghold:chests/brewing', 25],
  ['bookshelf_mastery', 'integrated_stronghold:chests/enchanting', 25],
  ['bookshelf_mastery', 'integrated_stronghold:chests/grand_library', 25],
  ['bookshelf_mastery', 'integrated_stronghold:chests/sanctorum', 25],
  // -- boss_trophy_relics --
  ['boss_trophy_relics', 'ati_structures:chests/ingredients', 7],
  ['boss_trophy_relics', 'burnt:chest_loot', 7],
  ['boss_trophy_relics', 'burnt:grave_loot', 7],
  ['boss_trophy_relics', 'chalk:chests/abandoned_mineshaft_chalk_loot', 7],
  ['boss_trophy_relics', 'create_ltab:core/basic_loot', 7],
  ['boss_trophy_relics', 'minecraft:chests/wood', 7],
  // -- bread_of_the_black_land --
  ['bread_of_the_black_land', 'abridged:chests/badlands_mining', 25],
  ['bread_of_the_black_land', 'beachparty:chests/desert_pyramid', 25],
  ['bread_of_the_black_land', 'betterdeserttemples:chests/food_storage', 25],
  ['bread_of_the_black_land', 'betterdeserttemples:chests/lab', 25],
  ['bread_of_the_black_land', 'minecraft:chests/desert_pyramid', 25],
  ['bread_of_the_black_land', 'minecraft:chests/village/village_desert_house', 25],
  // -- brewers_cellar --
  ['brewers_cellar', 'minecraft:chests/village/village_mason', 25],
  ['brewers_cellar', 'minecraft:chests/village/village_plains_house', 25],
  ['brewers_cellar', 'minecraft:chests/village/village_savanna_house', 25],
  ['brewers_cellar', 'minecraft:chests/village/village_temple', 25],
  ['brewers_cellar', 'minecraft:chests/village/village_toolsmith', 25],
  ['brewers_cellar', 'minecraft:chests/village/village_weaponsmith', 25],
  // -- bruisers_creed --
  ['bruisers_creed', 'dungeonnowloading:chests/temple_of_duality/armor/easy_combat', 17],
  ['bruisers_creed', 'dungeonnowloading:chests/temple_of_duality/armor/easy_puzzle', 17],
  ['bruisers_creed', 'dungeonnowloading:chests/temple_of_duality/armor/hard_combat', 17],
  ['bruisers_creed', 'dungeonnowloading:chests/temple_of_duality/armor/hard_puzzle', 17],
  ['bruisers_creed', 'dungeonnowloading:chests/temple_of_duality/armor/normal_combat', 17],
  ['bruisers_creed', 'dungeonnowloading:chests/temple_of_duality/armor/normal_puzzle', 17],
  // -- cannoneer --
  ['cannoneer', 'ati_structures:chests/potion_storage', 17],
  ['cannoneer', 'ati_structures:chests/stone_storage', 17],
  ['cannoneer', 'ati_structures:chests/wood_storage', 17],
  ['cannoneer', 'integrated_stronghold:chests/storage', 17],
  ['cannoneer', 'irons_spellbooks:chests/component_storage', 17],
  ['cannoneer', 'irons_spellbooks:chests/filler_storage_loot', 17],
  // -- carnal_anatomy --
  ['carnal_anatomy', 'alexscaves:chests/abyssal_ruins', 7],
  ['carnal_anatomy', 'alexscaves:chests/caveman_house', 7],
  ['carnal_anatomy', 'alexscaves:chests/forlorn_ruins', 7],
  ['carnal_anatomy', 'alexscaves:chests/gingerbread_town', 7],
  ['carnal_anatomy', 'alexscaves:chests/licowitch_tower', 7],
  ['carnal_anatomy', 'alexscaves:chests/licowitch_tower_secret', 7],
  // -- cartography_advanced --
  ['cartography_advanced', 'burnt:grave_loot', 25],
  ['cartography_advanced', 'chalk:chests/abandoned_mineshaft_chalk_loot', 25],
  ['cartography_advanced', 'create_ltab:core/basic_loot', 25],
  ['cartography_advanced', 'create_ltab:core/legend_loot', 25],
  ['cartography_advanced', 'create_ltab:core/rare_loot', 25],
  ['cartography_advanced', 'create_ltab:normal/basic_loot', 25],
  // -- cataclysm_codex --
  ['cataclysm_codex', 'beachparty:chests/buried_treasure', 11],
  ['cataclysm_codex', 'cataclysm:chests/acropolis_treasure', 11],
  ['cataclysm_codex', 'cataclysm:chests/burning_arena_reward', 11],
  ['cataclysm_codex', 'minecraft:chests/buried_treasure', 11],
  ['cataclysm_codex', 'minecraft:chests/trial_chambers/reward', 11],
  ['cataclysm_codex', 'minecraft:chests/trial_chambers/reward_ominous', 11],
  // -- civ_scrollwright --
  ['civ_scrollwright', 'integrated_stronghold:chests/enchanting', 15],
  ['civ_scrollwright', 'integrated_stronghold:chests/grand_library', 15],
  ['civ_scrollwright', 'integrated_stronghold:chests/sanctorum', 15],
  ['civ_scrollwright', 'integrated_stronghold:chests/stronghold', 15],
  ['civ_scrollwright', 'irons_spellbooks:chests/additional_library_loot', 15],
  ['civ_scrollwright', 'irons_spellbooks:chests/bookshelf_loot', 15],
  // -- codex_of_kukulkan --
  ['codex_of_kukulkan', 'betterjungletemples:chests/campsite', 25],
  ['codex_of_kukulkan', 'betterjungletemples:chests/treasure', 25],
  ['codex_of_kukulkan', 'call_of_yucutan:chest/crypt_chest_loot', 25],
  ['codex_of_kukulkan', 'call_of_yucutan:chest/overgrown_chest_loot', 25],
  ['codex_of_kukulkan', 'minecraft:chests/jungle_temple', 25],
  ['codex_of_kukulkan', 'minecraft:chests/village/village_jungle_house', 25],
  // -- cold_sweat_discipline --
  ['cold_sweat_discipline', 'farmersdelight:chests/fd_village_snowy_house', 35],
  ['cold_sweat_discipline', 'farmersdelight:chests/fd_village_taiga_house', 35],
  ['cold_sweat_discipline', 'irons_spellbooks:chests/mountain_tower/ice_barrel', 35],
  ['cold_sweat_discipline', 'minecraft:chests/igloo_chest', 35],
  ['cold_sweat_discipline', 'minecraft:chests/village/village_snowy_house', 35],
  ['cold_sweat_discipline', 'minecraft:chests/village/village_taiga_house', 35],
  // -- command_ruin --
  ['command_ruin', 'dungeonnowloading:chests/temple_of_duality/armor/hard_puzzle', 10],
  ['command_ruin', 'dungeonnowloading:chests/temple_of_duality/armor/normal_combat', 10],
  ['command_ruin', 'dungeonnowloading:chests/temple_of_duality/armor/normal_puzzle', 10],
  ['command_ruin', 'dungeonnowloading:chests/temple_of_duality/arrow/easy_combat', 10],
  ['command_ruin', 'dungeonnowloading:chests/temple_of_duality/arrow/easy_puzzle', 10],
  ['command_ruin', 'dungeonnowloading:chests/temple_of_duality/arrow/hard_combat', 10],
  // -- companions_charter --
  ['companions_charter', 'ctov:chests/village/village_mushroom_house', 7],
  ['companions_charter', 'farmersdelight:chests/fd_village_butcher', 7],
  ['companions_charter', 'irons_spellbooks:chests/mangrove_hut', 7],
  ['companions_charter', 'irons_spellbooks:chests/wheat', 7],
  ['companions_charter', 'mowziesmobs:chests/umvuthana_grove_chest', 7],
  ['companions_charter', 'revampedvillages:professions/butcher', 7],
  // -- confectioners_hollow --
  ['confectioners_hollow', 'chalk:chests/village_chalk_loot', 17],
  ['confectioners_hollow', 'chefsdelight:chests/cooker', 17],
  ['confectioners_hollow', 'ctov:chests/village/village_bakery', 17],
  ['confectioners_hollow', 'minecraft:chests/village/village_temple', 17],
  ['confectioners_hollow', 'minecraft:chests/village/village_toolsmith', 17],
  ['confectioners_hollow', 'minecraft:chests/village/village_weaponsmith', 17],
  // -- cookware_advanced --
  ['cookware_advanced', 'chalk:chests/village_chalk_loot', 12],
  ['cookware_advanced', 'chefsdelight:chests/cooker', 12],
  ['cookware_advanced', 'ctov:chests/village/village_bakery', 12],
  ['cookware_advanced', 'ctov:chests/village/village_beach_house', 12],
  ['cookware_advanced', 'ctov:chests/village/village_dark_forest_house', 12],
  ['cookware_advanced', 'ctov:chests/village/village_mountain_house', 12],
  // -- cookware_forging --
  ['cookware_forging', 'ctov:chests/village/village_beach_house', 30],
  ['cookware_forging', 'ctov:chests/village/village_dark_forest_house', 30],
  ['cookware_forging', 'ctov:chests/village/village_mountain_house', 30],
  ['cookware_forging', 'ctov:chests/village/village_smith', 30],
  ['cookware_forging', 'ctov:chests/village/village_swamp_house', 30],
  ['cookware_forging', 'dungeons_and_combat:chests/hermit_house', 30],
  // -- curators_vitrine --
  ['curators_vitrine', 'integrated_stronghold:chests/stronghold', 25],
  ['curators_vitrine', 'irons_spellbooks:chests/additional_library_loot', 25],
  ['curators_vitrine', 'irons_spellbooks:chests/bookshelf_loot', 25],
  ['curators_vitrine', 'irons_spellbooks:chests/citadel/citadel_bookshelf', 25],
  ['curators_vitrine', 'irons_spellbooks:chests/citadel/citadel_tomes', 25],
  ['curators_vitrine', 'irons_spellbooks:chests/citadel/citadel_vault', 25],
  // -- delvers_grimoire --
  ['delvers_grimoire', 'alexscaves:chests/gingerbread_town', 17],
  ['delvers_grimoire', 'alexscaves:chests/licowitch_tower', 17],
  ['delvers_grimoire', 'alexscaves:chests/licowitch_tower_secret', 17],
  ['delvers_grimoire', 'alexscaves:chests/magnetic_ruins', 17],
  ['delvers_grimoire', 'alexscaves:chests/toxic_ruins', 17],
  ['delvers_grimoire', 'alexscaves:chests/underground_cabin', 17],
  // -- dragon_husbandry --
  ['dragon_husbandry', 'irons_spellbooks:chests/wheat', 12],
  ['dragon_husbandry', 'mowziesmobs:chests/umvuthana_grove_chest', 12],
  ['dragon_husbandry', 'revampedvillages:professions/butcher', 12],
  ['dragon_husbandry', 'revampedvillages:professions/fisherman', 12],
  ['dragon_husbandry', 'revampedvillages:professions/leatherworker', 12],
  ['dragon_husbandry', 'revampedvillages:professions/shepherd', 12],
  // -- dragonslayer_codex --
  ['dragonslayer_codex', 'dungeonnowloading:chests/temple_of_duality/arrow/easy_combat', 17],
  ['dragonslayer_codex', 'dungeonnowloading:chests/temple_of_duality/arrow/easy_puzzle', 17],
  ['dragonslayer_codex', 'dungeonnowloading:chests/temple_of_duality/arrow/hard_combat', 17],
  ['dragonslayer_codex', 'dungeonnowloading:chests/temple_of_duality/arrow/hard_puzzle', 17],
  ['dragonslayer_codex', 'dungeonnowloading:chests/temple_of_duality/arrow/normal_combat', 17],
  ['dragonslayer_codex', 'dungeonnowloading:chests/temple_of_duality/arrow/normal_puzzle', 17],
  // -- dwemer_observatory --
  ['dwemer_observatory', 'create_ltab:core/legend_loot', 4],
  ['dwemer_observatory', 'create_ltab:core/rare_loot', 4],
  ['dwemer_observatory', 'create_ltab:normal/basic_loot', 4],
  ['dwemer_observatory', 'create_ltab:normal/legend_loot', 4],
  ['dwemer_observatory', 'create_ltab:normal/rare_loot', 4],
  ['dwemer_observatory', 'create_ltab:normal/trash_loot', 4],
  // -- dyecraft --
  ['dyecraft', 'exposure:chests/village_plains_house', 25],
  ['dyecraft', 'farmersdelight:chests/fd_village_plains_house', 25],
  ['dyecraft', 'minecraft:chests/village/village_mason', 25],
  ['dyecraft', 'minecraft:chests/village/village_plains_house', 25],
  ['dyecraft', 'minecraft:chests/village/village_savanna_house', 25],
  ['dyecraft', 'wares:chests/village/badlands_warehouse', 25],
  ['dyecraft', 'wares:chests/village/beach_warehouse', 25],
  // -- eldritch_school --
  ['eldritch_school', 'irons_spellbooks:chests/citadel/citadel_bookshelf', 17],
  ['eldritch_school', 'irons_spellbooks:chests/citadel/citadel_tomes', 17],
  ['eldritch_school', 'irons_spellbooks:chests/citadel/citadel_vault', 17],
  ['eldritch_school', 'irons_spellbooks:chests/citadel/rampart_chest', 17],
  ['eldritch_school', 'irons_spellbooks:chests/citadel/rampart_supplies', 17],
  ['eldritch_school', 'irons_spellbooks:chests/citadel/spawner_reward', 17],
  // -- electrical_engineering --
  ['electrical_engineering', 'integrated_stronghold:chests/storage', 17],
  ['electrical_engineering', 'irons_spellbooks:chests/component_storage', 17],
  ['electrical_engineering', 'irons_spellbooks:chests/filler_storage_loot', 17],
  ['electrical_engineering', 'irons_spellbooks:chests/mangrove_hut/hidden_potion_storage', 17],
  ['electrical_engineering', 'irons_spellbooks:chests/mangrove_hut/potion_ingredient_storage', 17],
  ['electrical_engineering', 'irons_spellbooks:chests/pyromancer_tower/pyromancer_basic_storage', 17],
  // -- end_architects_codex --
  ['end_architects_codex', 'farmersdelight:chests/fd_end_city_treasure', 11],
  ['end_architects_codex', 'irons_spellbooks:chests/additional_end_city_loot', 11],
  ['end_architects_codex', 'minecraft:chests/end_city_treasure', 11],
  ['end_architects_codex', 'tide:chests/crates/end', 11],
  ['end_architects_codex', 'traveloptics:chests/void_cathedral/hidden_sculk_room', 11],
  ['end_architects_codex', 'traveloptics:chests/void_cathedral/hidden_treasure_place', 11],
  // -- end_stoneworking --
  ['end_stoneworking', 'irons_spellbooks:chests/mangrove_hut/hidden_potion_storage', 11],
  ['end_stoneworking', 'irons_spellbooks:chests/mangrove_hut/potion_ingredient_storage', 11],
  ['end_stoneworking', 'irons_spellbooks:chests/pyromancer_tower/pyromancer_basic_storage', 11],
  ['end_stoneworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 11],
  ['end_stoneworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 11],
  ['end_stoneworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 11],
  // -- end_woodworking --
  ['end_woodworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 11],
  ['end_woodworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 11],
  ['end_woodworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 11],
  ['end_woodworking', 'mebahelcreaturesdwarven:chests/dwemer_tower', 11],
  ['end_woodworking', 'traveloptics:chests/aqua_mage_tower/aqua_mage_basic_storage', 11],
  ['end_woodworking', 'traveloptics:chests/aqua_mage_tower/aqua_mage_treasure_storage', 11],
  // -- ender_school --
  ['ender_school', 'irons_spellbooks:chests/citadel/rampart_chest', 10],
  ['ender_school', 'irons_spellbooks:chests/citadel/rampart_supplies', 10],
  ['ender_school', 'irons_spellbooks:chests/citadel/spawner_reward', 10],
  ['ender_school', 'irons_spellbooks:chests/evoker_fort', 10],
  ['ender_school', 'irons_spellbooks:chests/evoker_fort/guard_tower', 10],
  ['ender_school', 'irons_spellbooks:chests/generic_magic_treasure', 10],
  // -- evocation_school --
  ['evocation_school', 'irons_spellbooks:chests/evoker_fort', 17],
  ['evocation_school', 'irons_spellbooks:chests/evoker_fort/guard_tower', 17],
  ['evocation_school', 'irons_spellbooks:chests/generic_magic_treasure', 17],
  ['evocation_school', 'irons_spellbooks:chests/ice_spider_den/tower', 17],
  ['evocation_school', 'irons_spellbooks:chests/magic_bookshelf_loot', 17],
  ['evocation_school', 'irons_spellbooks:chests/mountain_tower/mountain_tower', 17],
  // -- eye_abyssal --
  ['eye_abyssal', 'aquamirae:chests/frozen_chest', 11],
  ['eye_abyssal', 'aquamirae:chests/maze_camp_chest', 11],
  ['eye_abyssal', 'aquamirae:chests/maze_common_chest', 11],
  ['eye_abyssal', 'aquamirae:chests/ship_1', 11],
  ['eye_abyssal', 'minecraft:chests/underwater_ruin_big', 11],
  ['eye_abyssal', 'minecraft:chests/underwater_ruin_small', 11],
  // -- eye_black --
  ['eye_black', 'beachparty:chests/desert_pyramid', 11],
  ['eye_black', 'betterdeserttemples:chests/food_storage', 11],
  ['eye_black', 'betterdeserttemples:chests/lab', 11],
  ['eye_black', 'betterdeserttemples:chests/library', 11],
  ['eye_black', 'betterdeserttemples:chests/pharaoh_hidden', 11],
  ['eye_black', 'betterdeserttemples:chests/pot', 11],
  // -- eye_cold --
  ['eye_cold', 'farmersdelight:chests/fd_village_snowy_house', 11],
  ['eye_cold', 'farmersdelight:chests/fd_village_taiga_house', 11],
  ['eye_cold', 'irons_spellbooks:chests/mountain_tower/ice_barrel', 11],
  ['eye_cold', 'ramadandelight:chests/rd_village_snowy_house', 11],
  ['eye_cold', 'ramadandelight:chests/rd_village_taiga_house', 11],
  ['eye_cold', 'revampedvillages:snowy_common', 11],
  // -- eye_corrupted --
  ['eye_corrupted', 'alexscaves:chests/magnetic_ruins', 11],
  ['eye_corrupted', 'alexscaves:chests/toxic_ruins', 11],
  ['eye_corrupted', 'alexscaves:chests/underground_cabin', 11],
  ['eye_corrupted', 'alexscaves:chests/underground_cabin_abyssal_chasm', 11],
  ['eye_corrupted', 'alexscaves:chests/underground_cabin_candy_cavity', 11],
  ['eye_corrupted', 'alexscaves:chests/underground_cabin_forlorn_hollows', 11],
  // -- eye_cryptic --
  ['eye_cryptic', 'mebahelcreaturesdwarven:chests/dwemer_tower', 11],
  ['eye_cryptic', 'traveloptics:chests/aqua_mage_tower/aqua_mage_basic_storage', 11],
  ['eye_cryptic', 'traveloptics:chests/aqua_mage_tower/aqua_mage_treasure_storage', 11],
  ['eye_cryptic', 'wares:chests/village/badlands_warehouse', 11],
  ['eye_cryptic', 'wares:chests/village/beach_warehouse', 11],
  ['eye_cryptic', 'wares:chests/village/dark_forest_warehouse', 11],
  // -- eye_cursed --
  ['eye_cursed', 'alexscaves:chests/underground_cabin_abyssal_chasm', 11],
  ['eye_cursed', 'alexscaves:chests/underground_cabin_candy_cavity', 11],
  ['eye_cursed', 'alexscaves:chests/underground_cabin_forlorn_hollows', 11],
  ['eye_cursed', 'alexscaves:chests/underground_cabin_magnetic_caves', 11],
  ['eye_cursed', 'alexscaves:chests/underground_cabin_primordial_caves', 11],
  ['eye_cursed', 'alexscaves:chests/underground_cabin_toxic_caves', 11],
  // -- eye_desert --
  ['eye_desert', 'betterdeserttemples:chests/library', 11],
  ['eye_desert', 'betterdeserttemples:chests/pharaoh_hidden', 11],
  ['eye_desert', 'betterdeserttemples:chests/pot', 11],
  ['eye_desert', 'betterdeserttemples:chests/statue', 11],
  ['eye_desert', 'betterdeserttemples:chests/storage', 11],
  ['eye_desert', 'betterdeserttemples:chests/tomb', 11],
  // -- eye_evil --
  ['eye_evil', 'celestisynth:chests/vanilla_nether_structures', 11],
  ['eye_evil', 'create_ltab:nether/basic_loot', 11],
  ['eye_evil', 'minecraft:chests/bastion_treasure', 11],
  ['eye_evil', 'minecraft:chests/nether_bridge', 11],
  ['eye_evil', 'minecraft:chests/nether_totemloot', 11],
  ['eye_evil', 'minecraft:chests/ruined_portal', 11],
  // -- eye_exotic --
  ['eye_exotic', 'betterjungletemples:chests/treasure', 11],
  ['eye_exotic', 'call_of_yucutan:chest/crypt_chest_loot', 11],
  ['eye_exotic', 'call_of_yucutan:chest/overgrown_chest_loot', 11],
  ['eye_exotic', 'ctov:chests/village/village_jungle_house', 11],
  ['eye_exotic', 'minecraft:chests/jungle_temple', 11],
  ['eye_exotic', 'minecraft:chests/village/village_jungle_house', 11],
  // -- eye_flame --
  ['eye_flame', 'celestisynth:chests/vanilla_nether_structures', 11],
  ['eye_flame', 'create_ltab:nether/basic_loot', 11],
  ['eye_flame', 'dungeons_and_combat:chests/blazing_fortress_loot', 11],
  ['eye_flame', 'dungeons_and_combat:chests/infernal_fortress', 11],
  ['eye_flame', 'farmersdelight:chests/fd_bastion_hoglin_stable', 11],
  ['eye_flame', 'minecraft:chests/ruined_portal', 11],
  // -- eye_frostmaw --
  ['eye_frostmaw', 'ramadandelight:chests/rd_village_snowy_house', 11],
  ['eye_frostmaw', 'ramadandelight:chests/rd_village_taiga_house', 11],
  ['eye_frostmaw', 'revampedvillages:snowy_common', 11],
  ['eye_frostmaw', 'revampedvillages:taiga_common', 11],
  ['eye_frostmaw', 'traveloptics:chests/frosted_prison_treasure_additions', 11],
  ['eye_frostmaw', 'vintagedelight:chests/vd_village_snowy_house', 11],
  // -- eye_guardian --
  ['eye_guardian', 'aquamirae:chests/maze_camp_chest', 11],
  ['eye_guardian', 'aquamirae:chests/maze_common_chest', 11],
  ['eye_guardian', 'aquamirae:chests/ship_1', 11],
  ['eye_guardian', 'aquamirae:chests/ship_2', 11],
  ['eye_guardian', 'ati_structures:chests/aqua', 11],
  ['eye_guardian', 'beachparty:chests/shipwreck_supply', 11],
  // -- eye_lost --
  ['eye_lost', 'betterjungletemples:chests/campsite', 11],
  ['eye_lost', 'betterjungletemples:chests/treasure', 11],
  ['eye_lost', 'call_of_yucutan:chest/crypt_chest_loot', 11],
  ['eye_lost', 'ctov:chests/village/village_jungle_house', 11],
  ['eye_lost', 'minecraft:chests/jungle_temple', 11],
  ['eye_lost', 'minecraft:chests/village/village_jungle_house', 11],
  // -- eye_magical --
  ['eye_magical', 'irons_spellbooks:chests/ice_spider_den/tower', 11],
  ['eye_magical', 'irons_spellbooks:chests/magic_bookshelf_loot', 11],
  ['eye_magical', 'irons_spellbooks:chests/mountain_tower/mountain_tower', 11],
  ['eye_magical', 'irons_spellbooks:chests/priest_house', 11],
  ['eye_magical', 'irons_spellbooks:chests/pyromancer_tower/burnt_chest', 11],
  ['eye_magical', 'irons_spellbooks:chests/pyromancer_tower/fire_ale_cask', 11],
  // -- eye_mech --
  ['eye_mech', 'wares:chests/village/badlands_warehouse', 11],
  ['eye_mech', 'wares:chests/village/beach_warehouse', 11],
  ['eye_mech', 'wares:chests/village/dark_forest_warehouse', 11],
  ['eye_mech', 'wares:chests/village/jungle_warehouse', 11],
  ['eye_mech', 'wares:chests/village/mountain_warehouse', 11],
  ['eye_mech', 'wares:chests/village/mushroom_warehouse', 11],
  // -- eye_monstrous --
  ['eye_monstrous', 'alexscaves:chests/underground_cabin_magnetic_caves', 11],
  ['eye_monstrous', 'alexscaves:chests/underground_cabin_primordial_caves', 11],
  ['eye_monstrous', 'alexscaves:chests/underground_cabin_toxic_caves', 11],
  ['eye_monstrous', 'alexscaves:chests/witch_hut', 11],
  ['eye_monstrous', 'alexscaves:entities/nucleeper', 11],
  ['eye_monstrous', 'dungeons_and_combat:chests/catacumbs', 11],
  // -- eye_nether --
  ['eye_nether', 'dungeons_and_combat:chests/blazing_fortress_loot', 11],
  ['eye_nether', 'dungeons_and_combat:chests/infernal_fortress', 11],
  ['eye_nether', 'farmersdelight:chests/fd_bastion_hoglin_stable', 11],
  ['eye_nether', 'farmersdelight:chests/fd_bastion_treasure', 11],
  ['eye_nether', 'farmersdelight:chests/fd_ruined_portal', 11],
  ['eye_nether', 'frightsdelight:chests/frd_bastion_bridge', 11],
  // -- eye_nothingness --
  ['eye_nothingness', 'tide:chests/crates/end', 11],
  ['eye_nothingness', 'traveloptics:chests/void_cathedral/hidden_sculk_room', 11],
  ['eye_nothingness', 'traveloptics:chests/void_cathedral/hidden_treasure_place', 11],
  ['eye_nothingness', 'traveloptics:chests/void_cathedral/library_higher_basic', 11],
  ['eye_nothingness', 'traveloptics:chests/void_cathedral/library_higher_treasure', 11],
  ['eye_nothingness', 'traveloptics:chests/void_cathedral/library_lower_basic', 11],
  // -- eye_old --
  ['eye_old', 'alexscaves:chests/witch_hut', 11],
  ['eye_old', 'alexscaves:entities/nucleeper', 11],
  ['eye_old', 'dungeons_and_combat:chests/catacumbs', 11],
  ['eye_old', 'dungeons_and_combat:chests/ernos_cave_loot', 11],
  ['eye_old', 'dungeons_and_combat:chests/forgotten_sand', 11],
  ['eye_old', 'dungeons_and_combat:chests/forgotten_sand_treasure', 11],
  // -- eye_rogue --
  ['eye_rogue', 'minecraft:chests/rich_cart', 11],
  ['eye_rogue', 'minecraft:chests/village/village_cartographer', 11],
  ['eye_rogue', 'wares:chests/village/jungle_warehouse', 11],
  ['eye_rogue', 'wares:chests/village/mountain_warehouse', 11],
  ['eye_rogue', 'wares:chests/village/mushroom_warehouse', 11],
  ['eye_rogue', 'wares:chests/village/swamp_warehouse', 11],
  // -- eye_storm --
  ['eye_storm', 'traveloptics:chests/void_cathedral/library_higher_basic', 11],
  ['eye_storm', 'traveloptics:chests/void_cathedral/library_higher_treasure', 11],
  ['eye_storm', 'traveloptics:chests/void_cathedral/library_lower_basic', 11],
  ['eye_storm', 'traveloptics:chests/void_cathedral/library_lower_treasure', 11],
  ['eye_storm', 'traveloptics:chests/void_cathedral/silly_treasure', 11],
  ['eye_storm', 'true_end:chests/home', 11],
  // -- eye_sun --
  ['eye_sun', 'betterdeserttemples:chests/statue', 11],
  ['eye_sun', 'betterdeserttemples:chests/storage', 11],
  ['eye_sun', 'betterdeserttemples:chests/tomb', 11],
  ['eye_sun', 'betterdeserttemples:chests/tomb_pharaoh', 11],
  ['eye_sun', 'betterdeserttemples:chests/wardrobe', 11],
  ['eye_sun', 'chalk:chests/desert_pyramid_chalk_loot', 11],
  // -- eye_synthesis --
  ['eye_synthesis', 'beachparty:chests/buried_treasure', 4],
  ['eye_synthesis', 'cataclysm:chests/acropolis_treasure', 4],
  ['eye_synthesis', 'cataclysm:chests/burning_arena_reward', 4],
  ['eye_synthesis', 'cataclysm:chests/frosted_prison_treasure', 4],
  ['eye_synthesis', 'integrated_stronghold:chests/treasure', 4],
  ['eye_synthesis', 'irons_spellbooks:chests/additional_treasure_loot', 4],
  // -- eye_tongbi --
  ['eye_tongbi', 'dungeons_and_combat:chests/ernos_cave_loot', 11],
  ['eye_tongbi', 'dungeons_and_combat:chests/forgotten_sand', 11],
  ['eye_tongbi', 'dungeons_and_combat:chests/forgotten_sand_treasure', 11],
  ['eye_tongbi', 'integrated_stronghold:chests/crypt', 11],
  ['eye_tongbi', 'irons_spellbooks:chests/additional_ancient_city_loot', 11],
  ['eye_tongbi', 'irons_spellbooks:chests/battleground/burial_loot', 11],
  // -- eye_undead --
  ['eye_undead', 'integrated_stronghold:chests/crypt', 11],
  ['eye_undead', 'irons_spellbooks:chests/additional_ancient_city_loot', 11],
  ['eye_undead', 'irons_spellbooks:chests/battleground/burial_loot', 11],
  ['eye_undead', 'irons_spellbooks:chests/catacombs/armory_loot', 11],
  ['eye_undead', 'irons_spellbooks:chests/catacombs/coffin_loot', 11],
  ['eye_undead', 'irons_spellbooks:chests/catacombs/crypt_loot', 11],
  // -- eye_void --
  ['eye_void', 'minecraft:chests/end_city_treasure', 11],
  ['eye_void', 'traveloptics:chests/void_cathedral/library_lower_treasure', 11],
  ['eye_void', 'traveloptics:chests/void_cathedral/silly_treasure', 11],
  ['eye_void', 'true_end:chests/home', 11],
  ['eye_void', 'true_end:chests/home_farming_chest', 11],
  ['eye_void', 'true_end:chests/unknown_chest', 11],
  // -- eye_witch --
  ['eye_witch', 'irons_spellbooks:chests/priest_house', 11],
  ['eye_witch', 'irons_spellbooks:chests/pyromancer_tower/burnt_chest', 11],
  ['eye_witch', 'irons_spellbooks:chests/pyromancer_tower/fire_ale_cask', 11],
  ['eye_witch', 'irons_spellbooks:chests/pyromancer_tower/fire_ale_trove', 11],
  ['eye_witch', 'irons_spellbooks:chests/pyromancer_tower/old_cask', 11],
  ['eye_witch', 'irons_spellbooks:chests/pyromancer_tower/pot', 11],
  // -- eye_wither --
  ['eye_wither', 'farmersdelight:chests/fd_bastion_treasure', 11],
  ['eye_wither', 'farmersdelight:chests/fd_ruined_portal', 11],
  ['eye_wither', 'frightsdelight:chests/frd_bastion_bridge', 11],
  ['eye_wither', 'frightsdelight:chests/frd_bastion_other', 11],
  ['eye_wither', 'frightsdelight:chests/frd_bastion_treasure', 11],
  ['eye_wither', 'integrated_stronghold:chests/nether_portal', 11],
  // -- eye_wrought --
  ['eye_wrought', 'ati_structures:chests/coal_storage', 11],
  ['eye_wrought', 'ati_structures:chests/construction', 11],
  ['eye_wrought', 'ati_structures:chests/copper_storage', 11],
  ['eye_wrought', 'minecraft:chests/rich_cart', 11],
  ['eye_wrought', 'minecraft:chests/village/village_cartographer', 11],
  ['eye_wrought', 'wares:chests/village/swamp_warehouse', 11],
  // -- falconry --
  ['falconry', 'revampedvillages:professions/fisherman', 17],
  ['falconry', 'revampedvillages:professions/leatherworker', 17],
  ['falconry', 'revampedvillages:professions/shepherd', 17],
  ['falconry', 'roadweaver:chests/maid_house', 17],
  ['falconry', 'terralith:village/fortified/butcher', 17],
  ['falconry', 'vintagedelight:chests/mixed_seeds', 17],
  // -- feast_at_worlds_edge --
  ['feast_at_worlds_edge', 'farmersdelight:chests/fd_end_city_treasure', 10],
  ['feast_at_worlds_edge', 'irons_spellbooks:chests/additional_end_city_loot', 10],
  ['feast_at_worlds_edge', 'minecraft:chests/end_city_treasure', 10],
  ['feast_at_worlds_edge', 'tide:chests/crates/end', 10],
  ['feast_at_worlds_edge', 'true_end:chests/home_farming_chest', 10],
  ['feast_at_worlds_edge', 'true_end:chests/unknown_chest', 10],
  // -- field_medicine --
  ['field_medicine', 'irons_spellbooks:chests/pyromancer_tower/fire_ale_trove', 22],
  ['field_medicine', 'irons_spellbooks:chests/pyromancer_tower/old_cask', 22],
  ['field_medicine', 'irons_spellbooks:chests/pyromancer_tower/pot', 22],
  ['field_medicine', 'irons_spellbooks:chests/pyromancer_tower/pyromancer_supplies', 22],
  ['field_medicine', 'irons_spellbooks:chests/trial_chambers/additional_ominous_vault_loot', 22],
  ['field_medicine', 'irons_spellbooks:chests/trial_chambers/additional_regular_vault_loot', 22],
  // -- fire_school --
  ['fire_school', 'irons_spellbooks:chests/pyromancer_tower/pyromancer_supplies', 17],
  ['fire_school', 'irons_spellbooks:chests/trial_chambers/additional_ominous_vault_loot', 17],
  ['fire_school', 'irons_spellbooks:chests/trial_chambers/additional_regular_vault_loot', 17],
  ['fire_school', 'minecraft:chests/stronghold_corridor', 17],
  ['fire_school', 'mowziesmobs:chests/monastery_chest', 17],
  ['fire_school', 'terralith:village/fortified/library', 17],
  // -- fishing_arts --
  ['fishing_arts', 'aquamirae:chests/ship_2', 25],
  ['fishing_arts', 'ati_structures:chests/aqua', 25],
  ['fishing_arts', 'beachparty:chests/shipwreck_supply', 25],
  ['fishing_arts', 'beachparty:chests/shipwreck_treasure', 25],
  ['fishing_arts', 'beachparty:chests/underwater_ruin_big', 25],
  ['fishing_arts', 'beachparty:chests/underwater_ruin_small', 25],
  // -- five_vessels_apocrypha --
  ['five_vessels_apocrypha', 'cataclysm:chests/frosted_prison_treasure', 4],
  ['five_vessels_apocrypha', 'integrated_stronghold:chests/treasure', 4],
  ['five_vessels_apocrypha', 'irons_spellbooks:chests/additional_treasure_loot', 4],
  ['five_vessels_apocrypha', 'irons_spellbooks:chests/ice_spider_den/spawner_reward', 4],
  ['five_vessels_apocrypha', 'revampedvillages:treasure', 4],
  ['five_vessels_apocrypha', 'terralith:mage/treasure', 4],
  // -- foragers_almanac --
  ['foragers_almanac', 'minecraft:chests/village/village_butcher', 15],
  ['foragers_almanac', 'minecraft:chests/village/village_fisher', 15],
  ['foragers_almanac', 'minecraft:chests/village/village_shepherd', 15],
  ['foragers_almanac', 'roadweaver:chests/maid_house', 15],
  ['foragers_almanac', 'terralith:village/fortified/butcher', 15],
  ['foragers_almanac', 'vintagedelight:chests/mixed_seeds', 15],
  // -- forgetting_broth --
  // -- forlorn_hollows --
  ['forlorn_hollows', 'irons_spellbooks:chests/catacombs/armory_loot', 17],
  ['forlorn_hollows', 'irons_spellbooks:chests/catacombs/coffin_loot', 17],
  ['forlorn_hollows', 'irons_spellbooks:chests/catacombs/crypt_loot', 17],
  ['forlorn_hollows', 'irons_spellbooks:chests/catacombs/hidden_trough_treasure', 17],
  ['forlorn_hollows', 'irons_spellbooks:chests/catacombs/pot', 17],
  ['forlorn_hollows', 'irons_spellbooks:chests/catacombs/wall_loot', 17],
  // -- foundry_facade --
  ['foundry_facade', 'ati_structures:chests/construction', 17],
  ['foundry_facade', 'ati_structures:chests/stone_storage', 17],
  ['foundry_facade', 'exposure:chests/stronghold_crossing', 17],
  ['foundry_facade', 'integrated_stronghold:chests/bedroom', 17],
  ['foundry_facade', 'integrated_stronghold:chests/brewing', 17],
  ['foundry_facade', 'integrated_stronghold:chests/crypt', 17],
  ['foundry_facade', 'integrated_stronghold:chests/dining_hall', 17],
  // -- furnishers_hand --
  ['furnishers_hand', 'ctov:chests/village/village_beach_house', 25],
  ['furnishers_hand', 'ctov:chests/village/village_dark_forest_house', 25],
  ['furnishers_hand', 'ctov:chests/village/village_mountain_house', 25],
  ['furnishers_hand', 'exposure:chests/village_plains_house', 25],
  ['furnishers_hand', 'farmersdelight:chests/fd_village_plains_house', 25],
  ['furnishers_hand', 'farmersdelight:chests/fd_village_taiga_house', 25],
  ['furnishers_hand', 'minecraft:chests/village/village_plains_house', 25],
  // -- furniturecraft --
  ['furniturecraft', 'ctov:chests/village/village_beach_house', 25],
  ['furniturecraft', 'ctov:chests/village/village_dark_forest_house', 25],
  ['furniturecraft', 'ctov:chests/village/village_mountain_house', 25],
  ['furniturecraft', 'exposure:chests/village_plains_house', 25],
  ['furniturecraft', 'farmersdelight:chests/fd_village_plains_house', 25],
  ['furniturecraft', 'farmersdelight:chests/fd_village_taiga_house', 25],
  ['furniturecraft', 'minecraft:chests/village/village_plains_house', 25],
  // -- gallery_broth --
  ['gallery_broth', 'irons_spellbooks:chests/catacombs/hidden_trough_treasure', 25],
  ['gallery_broth', 'irons_spellbooks:chests/catacombs/pot', 25],
  ['gallery_broth', 'irons_spellbooks:chests/catacombs/wall_loot', 25],
  ['gallery_broth', 'traveloptics:chests/abyssal_ruins_additions', 25],
  ['gallery_broth', 'traveloptics:chests/ancient_city_additions', 25],
  ['gallery_broth', 'traveloptics:chests/ancient_city_ice_additions', 25],
  // -- gardened_wash --
  ['gardened_wash', 'ctov:chests/village/village_farm', 35],
  ['gardened_wash', 'ctov:chests/village/village_forager', 35],
  ['gardened_wash', 'minecraft:chests/village/village_butcher', 35],
  ['gardened_wash', 'minecraft:chests/village/village_fisher', 35],
  ['gardened_wash', 'minecraft:chests/village/village_shepherd', 35],
  ['gardened_wash', 'minecraft:chests/village/village_tannery', 35],
  // -- glassworking --
  ['glassworking', 'beachparty:chests/desert_pyramid', 35],
  ['glassworking', 'chalk:chests/desert_pyramid_chalk_loot', 35],
  ['glassworking', 'exposure:chests/village_plains_house', 35],
  ['glassworking', 'farmersdelight:chests/fd_village_plains_house', 35],
  ['glassworking', 'minecraft:chests/desert_pyramid', 35],
  ['glassworking', 'minecraft:chests/village/village_mason', 35],
  ['glassworking', 'minecraft:chests/village/village_plains_house', 35],
  // -- god_scarlet_king --
  ['god_scarlet_king', 'frightsdelight:chests/frd_bastion_other', 6],
  ['god_scarlet_king', 'frightsdelight:chests/frd_bastion_treasure', 6],
  ['god_scarlet_king', 'integrated_stronghold:chests/nether_portal', 6],
  ['god_scarlet_king', 'irons_spellbooks:chests/additional_nether_loot', 6],
  ['god_scarlet_king', 'irons_spellbooks:chests/battleground/piglin_camp', 6],
  ['god_scarlet_king', 'mynethersdelight:chests/mnd_bastion_hoglin_stable', 6],
  // -- gravitic_engineering --
  ['gravitic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 15],
  ['gravitic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 15],
  ['gravitic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 15],
  ['gravitic_engineering', 'mebahelcreaturesdwarven:chests/dwemer_tower', 15],
  // -- gunsmithing --
  ['gunsmithing', 'ati_structures:chests/coal_storage', 13],
  ['gunsmithing', 'ati_structures:chests/construction', 13],
  ['gunsmithing', 'ati_structures:chests/copper_storage', 13],
  ['gunsmithing', 'ati_structures:chests/food_storage', 13],
  ['gunsmithing', 'ati_structures:chests/gold_storage', 13],
  ['gunsmithing', 'ati_structures:chests/iron_storage', 13],
  // -- heavy_plate_discipline --
  ['heavy_plate_discipline', 'dungeonnowloading:chests/temple_of_duality/arrow/hard_puzzle', 12],
  ['heavy_plate_discipline', 'dungeonnowloading:chests/temple_of_duality/arrow/normal_combat', 12],
  ['heavy_plate_discipline', 'dungeonnowloading:chests/temple_of_duality/arrow/normal_puzzle', 12],
  ['heavy_plate_discipline', 'dungeonnowloading:chests/temple_of_duality/book/easy_combat', 12],
  ['heavy_plate_discipline', 'dungeonnowloading:chests/temple_of_duality/book/easy_puzzle', 12],
  ['heavy_plate_discipline', 'dungeonnowloading:chests/temple_of_duality/book/hard_combat', 12],
  // -- holy_school --
  ['holy_school', 'ati_structures:chests/library', 17],
  ['holy_school', 'minecraft:chests/stronghold_corridor', 17],
  ['holy_school', 'minecraft:chests/stronghold_crossing', 17],
  ['holy_school', 'minecraft:chests/stronghold_library', 17],
  ['holy_school', 'mowziesmobs:chests/monastery_chest', 17],
  ['holy_school', 'terralith:village/fortified/library', 17],
  // -- ice_school --
  ['ice_school', 'ati_structures:chests/library', 17],
  ['ice_school', 'ctov:chests/village/village_library', 17],
  ['ice_school', 'exposure:chests/stronghold_crossing', 17],
  ['ice_school', 'ice_and_fire_spellbooks:chests/fodaan_mask', 17],
  ['ice_school', 'minecraft:chests/stronghold_crossing', 17],
  ['ice_school', 'minecraft:chests/stronghold_library', 17],
  // -- infernal_passage --
  ['infernal_passage', 'irons_spellbooks:chests/additional_nether_loot', 15],
  ['infernal_passage', 'irons_spellbooks:chests/battleground/piglin_camp', 15],
  ['infernal_passage', 'mynethersdelight:chests/mnd_bastion_hoglin_stable', 15],
  ['infernal_passage', 'mynethersdelight:chests/mnd_bastion_treasure', 15],
  ['infernal_passage', 'mythsandlegends:blocks/ancient_vestiges_chest', 15],
  ['infernal_passage', 'mythsandlegends:blocks/scorched_chest', 15],
  // overworld ruined portals (the gateway) , breaks the nether chicken-and-egg
  ['infernal_passage', 'minecraft:chests/ruined_portal', 15],
  ['infernal_passage', 'farmersdelight:chests/fd_ruined_portal', 15],
  ['infernal_passage', 'nethervinery:chests/ruined_portal', 15],
  ['infernal_passage', 'vintagedelight:chests/vd_ruined_portal', 15],
  // -- joiners_frame --
  ['joiners_frame', 'ctov:chests/village/village_beach_house', 25],
  ['joiners_frame', 'ctov:chests/village/village_dark_forest_house', 25],
  ['joiners_frame', 'ctov:chests/village/village_mountain_house', 25],
  ['joiners_frame', 'exposure:chests/village_plains_house', 25],
  ['joiners_frame', 'farmersdelight:chests/fd_village_plains_house', 25],
  ['joiners_frame', 'farmersdelight:chests/fd_village_taiga_house', 25],
  ['joiners_frame', 'minecraft:chests/village/village_plains_house', 25],
  // -- kept_creatures --
  ['kept_creatures', 'ctov:chests/village/village_farm', 7],
  ['kept_creatures', 'ctov:chests/village/village_forager', 7],
  ['kept_creatures', 'ctov:chests/village/village_mushroom_house', 7],
  ['kept_creatures', 'farmersdelight:chests/fd_village_butcher', 7],
  ['kept_creatures', 'irons_spellbooks:chests/mangrove_hut', 7],
  ['kept_creatures', 'minecraft:chests/village/village_tannery', 7],
  // -- kinetic_engineering --
  ['kinetic_engineering', 'ati_structures:chests/food_storage', 17],
  ['kinetic_engineering', 'ati_structures:chests/gold_storage', 17],
  ['kinetic_engineering', 'ati_structures:chests/iron_storage', 17],
  ['kinetic_engineering', 'ati_structures:chests/minerals', 17],
  ['kinetic_engineering', 'ati_structures:chests/potion_storage', 17],
  ['kinetic_engineering', 'ati_structures:chests/stone_storage', 17],
  // -- lamp_of_wishes --
  ['lamp_of_wishes', 'ctov:chests/village/village_library', 7],
  ['lamp_of_wishes', 'exposure:chests/stronghold_crossing', 7],
  ['lamp_of_wishes', 'ice_and_fire_spellbooks:chests/fodaan_mask', 7],
  ['lamp_of_wishes', 'ice_and_fire_spellbooks:chests/toornahkriin_mask', 7],
  ['lamp_of_wishes', 'ice_and_fire_spellbooks:chests/vulnilviir_mask', 7],
  ['lamp_of_wishes', 'ice_and_fire_spellbooks:chests/vulonqo_mask', 7],
  // -- lapidary_arts --
  ['lapidary_arts', 'ati_structures:chests/minerals', 12],
  ['lapidary_arts', 'ati_structures:chests/potion_storage', 12],
  ['lapidary_arts', 'ati_structures:chests/stone_storage', 12],
  ['lapidary_arts', 'ati_structures:chests/wood_storage', 12],
  ['lapidary_arts', 'integrated_stronghold:chests/storage', 12],
  ['lapidary_arts', 'irons_spellbooks:chests/component_storage', 12],
  // -- larder_methods --
  ['larder_methods', 'minecraft:chests/igloo_chest', 12],
  ['larder_methods', 'minecraft:chests/village/village_snowy_house', 12],
  ['larder_methods', 'revampedvillages:taiga_common', 12],
  ['larder_methods', 'traveloptics:chests/frosted_prison_treasure_additions', 12],
  ['larder_methods', 'vintagedelight:chests/vd_village_snowy_house', 12],
  ['larder_methods', 'vintagedelight:chests/vd_village_taiga_house', 12],
  // -- leatherworking --
  ['leatherworking', 'farmersdelight:chests/fd_village_butcher', 14],
  ['leatherworking', 'minecraft:chests/village/village_butcher', 14],
  ['leatherworking', 'minecraft:chests/village/village_fisher', 14],
  ['leatherworking', 'minecraft:chests/village/village_tannery', 14],
  ['leatherworking', 'revampedvillages:professions/leatherworker', 14],
  // -- lightning_school --
  ['lightning_school', 'ice_and_fire_spellbooks:chests/toornahkriin_mask', 17],
  ['lightning_school', 'ice_and_fire_spellbooks:chests/vulnilviir_mask', 17],
  ['lightning_school', 'ice_and_fire_spellbooks:chests/vulonqo_mask', 17],
  ['lightning_school', 'ice_and_fire_spellbooks:chests/vulsilah_mask', 17],
  ['lightning_school', 'integrated_stronghold:chests/brewing', 17],
  ['lightning_school', 'integrated_stronghold:chests/enchanting', 17],
  // -- lockwrights_irons --
  ['lockwrights_irons', 'ati_structures:chests/wood_storage', 35],
  ['lockwrights_irons', 'integrated_stronghold:chests/storage', 35],
  ['lockwrights_irons', 'irons_spellbooks:chests/component_storage', 35],
  ['lockwrights_irons', 'irons_spellbooks:chests/filler_storage_loot', 35],
  ['lockwrights_irons', 'irons_spellbooks:chests/mangrove_hut/hidden_potion_storage', 35],
  ['lockwrights_irons', 'irons_spellbooks:chests/mangrove_hut/potion_ingredient_storage', 35],
  // -- long_meal_before_firing --
  ['long_meal_before_firing', 'irons_spellbooks:chests/ice_spider_den/spawner_reward', 25],
  ['long_meal_before_firing', 'minecraft:chests/buried_treasure', 25],
  ['long_meal_before_firing', 'revampedvillages:treasure', 25],
  ['long_meal_before_firing', 'terralith:mage/treasure', 25],
  ['long_meal_before_firing', 'terralith:spire/treasure', 25],
  ['long_meal_before_firing', 'traveloptics:chests/acropolis_treasure_additions', 25],
  // -- long_road --
  ['long_road', 'create_ltab:normal/legend_loot', 25],
  ['long_road', 'create_ltab:normal/rare_loot', 25],
  ['long_road', 'create_ltab:normal/trash_loot', 25],
  ['long_road', 'create_ltab:snow/basic_loot', 25],
  ['long_road', 'create_ltab:water/basic_loot', 25],
  ['long_road', 'exposure:chests/abandoned_mineshaft', 25],
  // -- magnetic_deep --
  ['magnetic_deep', 'beachparty:chests/shipwreck_treasure', 17],
  ['magnetic_deep', 'beachparty:chests/underwater_ruin_big', 17],
  ['magnetic_deep', 'beachparty:chests/underwater_ruin_small', 17],
  ['magnetic_deep', 'betteroceanmonuments:chests/upper_side_chamber', 17],
  ['magnetic_deep', 'exposure:chests/shipwreck_map', 17],
  ['magnetic_deep', 'farmersdelight:chests/fd_shipwreck_supply', 17],
  // -- maize_codex --
  ['maize_codex', 'betterjungletemples:chests/campsite', 15],
  ['maize_codex', 'betterjungletemples:chests/treasure', 15],
  ['maize_codex', 'call_of_yucutan:chest/crypt_chest_loot', 15],
  ['maize_codex', 'call_of_yucutan:chest/overgrown_chest_loot', 15],
  ['maize_codex', 'ctov:chests/village/village_jungle_house', 15],
  ['maize_codex', 'minecraft:chests/jungle_temple', 15],
  // -- memory_of_the_baobab --
  ['memory_of_the_baobab', 'ctov:chests/village/village_mushroom_house', 35],
  ['memory_of_the_baobab', 'farmersdelight:chests/fd_village_butcher', 35],
  ['memory_of_the_baobab', 'irons_spellbooks:chests/mangrove_hut', 35],
  ['memory_of_the_baobab', 'irons_spellbooks:chests/wheat', 35],
  ['memory_of_the_baobab', 'mowziesmobs:chests/umvuthana_grove_chest', 35],
  ['memory_of_the_baobab', 'revampedvillages:professions/butcher', 35],
  // -- menagerie_of_the_wild --
  ['menagerie_of_the_wild', 'irons_spellbooks:chests/wheat', 17],
  ['menagerie_of_the_wild', 'mowziesmobs:chests/umvuthana_grove_chest', 17],
  ['menagerie_of_the_wild', 'revampedvillages:professions/butcher', 17],
  ['menagerie_of_the_wild', 'revampedvillages:professions/fisherman', 17],
  ['menagerie_of_the_wild', 'revampedvillages:professions/leatherworker', 17],
  ['menagerie_of_the_wild', 'revampedvillages:professions/shepherd', 17],
  // -- mender_lost_company --
  ['mender_lost_company', 'create_ltab:snow/basic_loot', 4],
  ['mender_lost_company', 'create_ltab:water/basic_loot', 4],
  ['mender_lost_company', 'exposure:chests/abandoned_mineshaft', 4],
  ['mender_lost_company', 'farmersdelight:chests/fd_abandoned_mineshaft', 4],
  ['mender_lost_company', 'integrated_stronghold:chests/bedroom', 4],
  ['mender_lost_company', 'integrated_stronghold:chests/dining_hall', 4],
  // -- mercantile_ledger --
  ['mercantile_ledger', 'irons_spellbooks:chests/filler_storage_loot', 35],
  ['mercantile_ledger', 'irons_spellbooks:chests/mangrove_hut/hidden_potion_storage', 35],
  ['mercantile_ledger', 'irons_spellbooks:chests/mangrove_hut/potion_ingredient_storage', 35],
  ['mercantile_ledger', 'irons_spellbooks:chests/pyromancer_tower/pyromancer_basic_storage', 35],
  ['mercantile_ledger', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 35],
  ['mercantile_ledger', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 35],
  // -- metalworking --
  ['metalworking', 'ati_structures:chests/iron_storage', 15],
  ['metalworking', 'ati_structures:chests/minerals', 15],
  ['metalworking', 'dungeons_and_combat:chests/blacksmithy', 15],
  ['metalworking', 'minecraft:chests/village/village_toolsmith', 15],
  ['metalworking', 'minecraft:chests/village/village_weaponsmith', 15],
  // -- mounted_rail --
  ['mounted_rail', 'irons_spellbooks:chests/pyromancer_tower/pyromancer_basic_storage', 17],
  ['mounted_rail', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 17],
  ['mounted_rail', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 17],
  ['mounted_rail', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 17],
  ['mounted_rail', 'mebahelcreaturesdwarven:chests/dwemer_tower', 17],
  ['mounted_rail', 'traveloptics:chests/aqua_mage_tower/aqua_mage_basic_storage', 17],
  // -- music_records --
  ['music_records', 'ice_and_fire_spellbooks:chests/vulsilah_mask', 25],
  ['music_records', 'integrated_stronghold:chests/brewing', 25],
  ['music_records', 'integrated_stronghold:chests/enchanting', 25],
  ['music_records', 'integrated_stronghold:chests/grand_library', 25],
  ['music_records', 'integrated_stronghold:chests/sanctorum', 25],
  ['music_records', 'integrated_stronghold:chests/stronghold', 25],
  // -- naturalist_basics --
  ['naturalist_basics', 'revampedvillages:professions/fisherman', 35],
  ['naturalist_basics', 'revampedvillages:professions/leatherworker', 35],
  ['naturalist_basics', 'revampedvillages:professions/shepherd', 35],
  ['naturalist_basics', 'roadweaver:chests/maid_house', 35],
  ['naturalist_basics', 'terralith:village/fortified/butcher', 35],
  ['naturalist_basics', 'vintagedelight:chests/mixed_seeds', 35],
  // -- nature_school --
  ['nature_school', 'integrated_stronghold:chests/grand_library', 17],
  ['nature_school', 'integrated_stronghold:chests/sanctorum', 17],
  ['nature_school', 'integrated_stronghold:chests/stronghold', 17],
  ['nature_school', 'irons_spellbooks:chests/additional_library_loot', 17],
  ['nature_school', 'irons_spellbooks:chests/bookshelf_loot', 17],
  ['nature_school', 'irons_spellbooks:chests/citadel/citadel_bookshelf', 17],
  // -- nether_architects_codex --
  ['nether_architects_codex', 'mynethersdelight:chests/mnd_bastion_treasure', 17],
  ['nether_architects_codex', 'mythsandlegends:blocks/ancient_vestiges_chest', 17],
  ['nether_architects_codex', 'mythsandlegends:blocks/scorched_chest', 17],
  ['nether_architects_codex', 'mythsandlegends:blocks/sepulcrum_ignitum_chest', 17],
  ['nether_architects_codex', 'netherexp:chests/chapel', 17],
  ['nether_architects_codex', 'netherexp:chests/sanctum_food', 17],
  // -- nether_stoneworking --
  ['nether_stoneworking', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 17],
  ['nether_stoneworking', 'mebahelcreaturesdwarven:chests/dwemer_tower', 17],
  ['nether_stoneworking', 'traveloptics:chests/aqua_mage_tower/aqua_mage_basic_storage', 17],
  ['nether_stoneworking', 'traveloptics:chests/aqua_mage_tower/aqua_mage_treasure_storage', 17],
  ['nether_stoneworking', 'wares:chests/village/badlands_warehouse', 17],
  ['nether_stoneworking', 'wares:chests/village/beach_warehouse', 17],
  // -- nether_woodworking --
  ['nether_woodworking', 'minecraft:chests/bastion_bridge', 17],
  ['nether_woodworking', 'minecraft:chests/bastion_hoglin_stable', 17],
  ['nether_woodworking', 'minecraft:chests/bastion_other', 17],
  ['nether_woodworking', 'mythsandlegends:blocks/sepulcrum_ignitum_chest', 17],
  ['nether_woodworking', 'netherexp:chests/chapel', 17],
  ['nether_woodworking', 'netherexp:chests/sanctum_food', 17],
  // -- numismatic_mechanisms --
  ['numismatic_mechanisms', 'traveloptics:chests/aqua_mage_tower/aqua_mage_treasure_storage', 17],
  ['numismatic_mechanisms', 'wares:chests/village/badlands_warehouse', 17],
  ['numismatic_mechanisms', 'wares:chests/village/beach_warehouse', 17],
  ['numismatic_mechanisms', 'wares:chests/village/dark_forest_warehouse', 17],
  ['numismatic_mechanisms', 'wares:chests/village/jungle_warehouse', 17],
  ['numismatic_mechanisms', 'wares:chests/village/mountain_warehouse', 17],
  // -- oddments_and_devices --
  ['oddments_and_devices', 'ctov:chests/village/village_smith', 17],
  ['oddments_and_devices', 'ctov:chests/village/village_swamp_house', 17],
  ['oddments_and_devices', 'dungeons_and_combat:chests/hermit_house', 17],
  ['oddments_and_devices', 'dungeons_and_combat:chests/tavern_loot', 17],
  ['oddments_and_devices', 'exposure:chests/village_plains_house', 17],
  ['oddments_and_devices', 'farmersdelight:chests/fd_village_plains_house', 17],
  // -- photography_arts --
  ['photography_arts', 'irons_spellbooks:chests/additional_library_loot', 14],
  ['photography_arts', 'irons_spellbooks:chests/bookshelf_loot', 14],
  ['photography_arts', 'irons_spellbooks:chests/citadel/citadel_bookshelf', 14],
  ['photography_arts', 'irons_spellbooks:chests/citadel/citadel_tomes', 14],
  ['photography_arts', 'irons_spellbooks:chests/citadel/citadel_vault', 14],
  ['photography_arts', 'irons_spellbooks:chests/citadel/rampart_chest', 14],
  // -- primordial_strata --
  ['primordial_strata', 'traveloptics:chests/abyssal_ruins_additions', 17],
  ['primordial_strata', 'traveloptics:chests/ancient_city_additions', 17],
  ['primordial_strata', 'traveloptics:chests/ancient_city_ice_additions', 17],
  ['primordial_strata', 'traveloptics:chests/catacombs_additions', 17],
  ['primordial_strata', 'traveloptics:chests/forlorn_ruins_additions_new', 17],
  ['primordial_strata', 'traveloptics:chests/magnetic_ruins_additions_new', 17],
  // -- quantum_gate --
  ['quantum_gate', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 4],
  ['quantum_gate', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 4],
  ['quantum_gate', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 4],
  ['quantum_gate', 'true_end:chests/home', 4],
  ['quantum_gate', 'true_end:chests/home_farming_chest', 4],
  ['quantum_gate', 'true_end:chests/unknown_chest', 4],
  // -- redstone_principles --
  ['redstone_principles', 'minecraft:chests/rich_cart', 14],
  ['redstone_principles', 'wares:chests/village/dark_forest_warehouse', 14],
  ['redstone_principles', 'wares:chests/village/jungle_warehouse', 14],
  ['redstone_principles', 'wares:chests/village/mountain_warehouse', 14],
  ['redstone_principles', 'wares:chests/village/mushroom_warehouse', 14],
  ['redstone_principles', 'wares:chests/village/swamp_warehouse', 14],
  // -- runesmithing --
  ['runesmithing', 'irons_spellbooks:chests/citadel/citadel_tomes', 17],
  ['runesmithing', 'irons_spellbooks:chests/citadel/citadel_vault', 17],
  ['runesmithing', 'irons_spellbooks:chests/citadel/rampart_chest', 17],
  ['runesmithing', 'irons_spellbooks:chests/citadel/rampart_supplies', 17],
  ['runesmithing', 'irons_spellbooks:chests/citadel/spawner_reward', 17],
  ['runesmithing', 'irons_spellbooks:chests/evoker_fort', 17],
  // -- scales_and_steel --
  ['scales_and_steel', 'minecraft:chests/village/village_butcher', 17],
  ['scales_and_steel', 'minecraft:chests/village/village_fisher', 17],
  ['scales_and_steel', 'minecraft:chests/village/village_shepherd', 17],
  ['scales_and_steel', 'roadweaver:chests/maid_house', 17],
  ['scales_and_steel', 'terralith:village/fortified/butcher', 17],
  ['scales_and_steel', 'vintagedelight:chests/mixed_seeds', 17],
  // -- scroll_end_passage --
  ['scroll_end_passage', 'traveloptics:chests/void_cathedral/hidden_sculk_room', 10],
  ['scroll_end_passage', 'traveloptics:chests/void_cathedral/hidden_treasure_place', 10],
  ['scroll_end_passage', 'traveloptics:chests/void_cathedral/library_higher_basic', 10],
  ['scroll_end_passage', 'traveloptics:chests/void_cathedral/library_higher_treasure', 10],
  ['scroll_end_passage', 'traveloptics:chests/void_cathedral/library_lower_basic', 10],
  ['scroll_end_passage', 'traveloptics:chests/void_cathedral/library_lower_treasure', 10],
  // -- sculk_sickness --
  ['sculk_sickness', 'minecraft:chests/ancient_city', 12],
  ['sculk_sickness', 'minecraft:chests/ancient_city_ice_box', 12],
  ['sculk_sickness', 'traveloptics:chests/catacombs_additions', 12],
  ['sculk_sickness', 'traveloptics:chests/forlorn_ruins_additions_new', 12],
  ['sculk_sickness', 'traveloptics:chests/magnetic_ruins_additions_new', 12],
  ['sculk_sickness', 'traveloptics:chests/toxic_ruins_additions_new', 12],
  // -- small_ships --
  ['small_ships', 'betteroceanmonuments:chests/upper_side_chamber', 25],
  ['small_ships', 'exposure:chests/shipwreck_map', 25],
  ['small_ships', 'farmersdelight:chests/fd_shipwreck_supply', 25],
  ['small_ships', 'irons_spellbooks:chests/impaled_icebreaker/captain_quarters', 25],
  ['small_ships', 'irons_spellbooks:chests/impaled_icebreaker/food_barrel', 25],
  ['small_ships', 'oceanic_delight:chests/ancient_fish_eggs_from_buried_treasure', 25],
  // -- smithing_legendary --
  ['smithing_legendary', 'ati_structures:chests/armory', 7],
  ['smithing_legendary', 'dungeons_and_combat:chests/blacksmithy', 7],
  ['smithing_legendary', 'irons_spellbooks:chests/catacombs/armory_loot', 7],
  ['smithing_legendary', 'minecraft:chests/village/village_toolsmith', 7],
  ['smithing_legendary', 'minecraft:chests/village/village_weaponsmith', 7],
  ['smithing_legendary', 'mythsandlegends:blocks/ancient_vestiges_chest', 7],
  ['smithing_legendary', 'mythsandlegends:blocks/sepulcrum_ignitum_chest', 7],
  // -- smithing_master --
  ['smithing_master', 'ati_structures:chests/armory', 17],
  ['smithing_master', 'dungeons_and_combat:chests/blacksmithy', 17],
  ['smithing_master', 'irons_spellbooks:chests/catacombs/armory_loot', 17],
  ['smithing_master', 'minecraft:chests/village/village_toolsmith', 17],
  ['smithing_master', 'minecraft:chests/village/village_weaponsmith', 17],
  ['smithing_master', 'mythsandlegends:blocks/ancient_vestiges_chest', 17],
  ['smithing_master', 'mythsandlegends:blocks/sepulcrum_ignitum_chest', 17],
  // -- sound_and_broadcast --
  ['sound_and_broadcast', 'irons_spellbooks:chests/citadel/rampart_supplies', 18],
  ['sound_and_broadcast', 'irons_spellbooks:chests/citadel/spawner_reward', 18],
  ['sound_and_broadcast', 'irons_spellbooks:chests/evoker_fort', 18],
  ['sound_and_broadcast', 'irons_spellbooks:chests/evoker_fort/guard_tower', 18],
  ['sound_and_broadcast', 'irons_spellbooks:chests/generic_magic_treasure', 18],
  ['sound_and_broadcast', 'irons_spellbooks:chests/ice_spider_den/tower', 18],
  // -- specialist_suits --
  ['specialist_suits', 'dungeonnowloading:chests/temple_of_duality/book/easy_combat', 17],
  ['specialist_suits', 'dungeonnowloading:chests/temple_of_duality/book/easy_puzzle', 17],
  ['specialist_suits', 'dungeonnowloading:chests/temple_of_duality/book/hard_combat', 17],
  ['specialist_suits', 'dungeonnowloading:chests/temple_of_duality/book/hard_puzzle', 17],
  ['specialist_suits', 'dungeonnowloading:chests/temple_of_duality/book/normal_combat', 17],
  ['specialist_suits', 'dungeonnowloading:chests/temple_of_duality/book/normal_puzzle', 17],
  // -- spoils_of_the_sea_roads --
  // -- steeping_kettle --
  ['steeping_kettle', 'minecraft:chests/miners_home', 25],
  ['steeping_kettle', 'minecraft:chests/village/village_armorer', 25],
  ['steeping_kettle', 'minecraft:chests/village/village_fletcher', 25],
  ['steeping_kettle', 'minecraft:chests/village/village_mason', 25],
  ['steeping_kettle', 'minecraft:chests/village/village_plains_house', 25],
  ['steeping_kettle', 'minecraft:chests/village/village_savanna_house', 25],
  // -- stolovaya_ledger --
  ['stolovaya_ledger', 'ati_structures:chests/coal_storage', 35],
  ['stolovaya_ledger', 'ati_structures:chests/construction', 35],
  ['stolovaya_ledger', 'minecraft:chests/rich_cart', 35],
  ['stolovaya_ledger', 'minecraft:chests/village/village_cartographer', 35],
  ['stolovaya_ledger', 'wares:chests/village/mushroom_warehouse', 35],
  ['stolovaya_ledger', 'wares:chests/village/swamp_warehouse', 35],
  // -- stoneworking --
  ['stoneworking', 'ati_structures:chests/stone_storage', 14],
  ['stoneworking', 'chalk:chests/abandoned_mineshaft_chalk_loot', 14],
  ['stoneworking', 'exposure:chests/abandoned_mineshaft', 14],
  ['stoneworking', 'farmersdelight:chests/fd_abandoned_mineshaft', 14],
  ['stoneworking', 'minecraft:chests/abandoned_mineshaft', 14],
  ['stoneworking', 'minecraft:chests/miners_home', 14],
  ['stoneworking', 'minecraft:chests/miners_ruined_shack', 14],
  // -- survivor_codex --
  ['survivor_codex', 'ctov:chests/village/village_farm', 25],
  ['survivor_codex', 'ctov:chests/village/village_forager', 25],
  ['survivor_codex', 'minecraft:chests/village/village_butcher', 25],
  ['survivor_codex', 'minecraft:chests/village/village_fisher', 25],
  ['survivor_codex', 'minecraft:chests/village/village_shepherd', 25],
  ['survivor_codex', 'minecraft:chests/village/village_tannery', 25],
  // -- teleportation_arts --
  ['teleportation_arts', 'mebahelcreaturesdwarven:chests/dwemer_ruin_common', 17],
  ['teleportation_arts', 'mebahelcreaturesdwarven:chests/dwemer_ruin_epic', 17],
  ['teleportation_arts', 'mebahelcreaturesdwarven:chests/dwemer_ruin_rare', 17],
  ['teleportation_arts', 'true_end:chests/home', 17],
  ['teleportation_arts', 'true_end:chests/home_farming_chest', 17],
  ['teleportation_arts', 'true_end:chests/unknown_chest', 17],
  // -- the_bestiary --
  ['the_bestiary', 'ctov:chests/village/village_farm', 15],
  ['the_bestiary', 'ctov:chests/village/village_forager', 15],
  ['the_bestiary', 'ctov:chests/village/village_mushroom_house', 15],
  ['the_bestiary', 'farmersdelight:chests/fd_village_butcher', 15],
  ['the_bestiary', 'irons_spellbooks:chests/mangrove_hut', 15],
  ['the_bestiary', 'minecraft:chests/village/village_tannery', 15],
  // -- the_pantry --
  ['the_pantry', 'minecraft:chests/village/village_mason', 35],
  ['the_pantry', 'minecraft:chests/village/village_plains_house', 35],
  ['the_pantry', 'minecraft:chests/village/village_savanna_house', 35],
  ['the_pantry', 'minecraft:chests/village/village_temple', 35],
  ['the_pantry', 'minecraft:chests/village/village_toolsmith', 35],
  ['the_pantry', 'minecraft:chests/village/village_weaponsmith', 35],
  // -- tidal_engineering --
  ['tidal_engineering', 'irons_spellbooks:chests/impaled_icebreaker/captain_quarters', 17],
  ['tidal_engineering', 'irons_spellbooks:chests/impaled_icebreaker/food_barrel', 17],
  ['tidal_engineering', 'oceanic_delight:chests/ancient_fish_eggs_from_buried_treasure', 17],
  ['tidal_engineering', 'ramadandelight:chests/rd_shipwreck_supply', 17],
  ['tidal_engineering', 'thirst:chests/shipwreck_supply', 17],
  ['tidal_engineering', 'thirst:chests/shipwreck_supply_bc', 17],
  // -- torch_and_lantern_craft --
  ['torch_and_lantern_craft', 'chalk:chests/village_chalk_loot', 35],
  ['torch_and_lantern_craft', 'chefsdelight:chests/cooker', 35],
  ['torch_and_lantern_craft', 'ctov:chests/village/village_bakery', 35],
  ['torch_and_lantern_craft', 'minecraft:chests/village/village_temple', 35],
  ['torch_and_lantern_craft', 'minecraft:chests/village/village_toolsmith', 35],
  ['torch_and_lantern_craft', 'minecraft:chests/village/village_weaponsmith', 35],
  // -- trim_smithing --
  ['trim_smithing', 'ati_structures:chests/armory', 35],
  ['trim_smithing', 'dungeons_and_combat:chests/blacksmithy', 35],
  ['trim_smithing', 'irons_spellbooks:chests/catacombs/armory_loot', 35],
  ['trim_smithing', 'minecraft:chests/village/village_toolsmith', 35],
  ['trim_smithing', 'minecraft:chests/village/village_weaponsmith', 35],
  ['trim_smithing', 'mythsandlegends:blocks/ancient_vestiges_chest', 35],
  ['trim_smithing', 'mythsandlegends:blocks/sepulcrum_ignitum_chest', 35],
  // -- two_larder_winter --
  ['two_larder_winter', 'farmersdelight:chests/fd_village_snowy_house', 25],
  ['two_larder_winter', 'farmersdelight:chests/fd_village_taiga_house', 25],
  ['two_larder_winter', 'minecraft:chests/igloo_chest', 25],
  ['two_larder_winter', 'minecraft:chests/village/village_snowy_house', 25],
  ['two_larder_winter', 'minecraft:chests/village/village_taiga_house', 25],
  ['two_larder_winter', 'vintagedelight:chests/vd_village_taiga_house', 25],
  // -- void_table --
  ['void_table', 'traveloptics:chests/void_cathedral/library_higher_treasure', 11],
  ['void_table', 'traveloptics:chests/void_cathedral/library_lower_basic', 11],
  ['void_table', 'traveloptics:chests/void_cathedral/library_lower_treasure', 11],
  ['void_table', 'traveloptics:chests/void_cathedral/silly_treasure', 11],
  ['void_table', 'true_end:chests/home', 11],
  ['void_table', 'true_end:chests/home_farming_chest', 11],
  // -- wayhouse_logistics --
  ['wayhouse_logistics', 'farmersdelight:chests/fd_abandoned_mineshaft', 35],
  ['wayhouse_logistics', 'integrated_stronghold:chests/bedroom', 35],
  ['wayhouse_logistics', 'integrated_stronghold:chests/dining_hall', 35],
  ['wayhouse_logistics', 'minecraft:chests/abandoned_mineshaft', 35],
  ['wayhouse_logistics', 'minecraft:chests/dye', 35],
  ['wayhouse_logistics', 'minecraft:chests/mineral', 35],
  // -- wild_study --
  ['wild_study', 'ctov:chests/village/village_mushroom_house', 18],
  ['wild_study', 'farmersdelight:chests/fd_village_butcher', 18],
  ['wild_study', 'irons_spellbooks:chests/mangrove_hut', 18],
  ['wild_study', 'irons_spellbooks:chests/wheat', 18],
  ['wild_study', 'mowziesmobs:chests/umvuthana_grove_chest', 18],
  ['wild_study', 'revampedvillages:professions/butcher', 18],
  // -- wilderness_camping --
  ['wilderness_camping', 'minecraft:chests/abandoned_mineshaft', 25],
  ['wilderness_camping', 'minecraft:chests/dye', 25],
  ['wilderness_camping', 'minecraft:chests/mineral', 25],
  ['wilderness_camping', 'minecraft:chests/miners_ruined_shack', 25],
  ['wilderness_camping', 'minecraft:chests/stone', 25],
  ['wilderness_camping', 'minecraft:chests/trial_chambers/supply', 25],
  // -- woodworking --
  ['woodworking', 'ati_structures:chests/wood_storage', 35],
  ['woodworking', 'chalk:chests/abandoned_mineshaft_chalk_loot', 35],
  ['woodworking', 'exposure:chests/abandoned_mineshaft', 35],
  ['woodworking', 'exposure:chests/village_plains_house', 35],
  ['woodworking', 'farmersdelight:chests/fd_abandoned_mineshaft', 35],
  ['woodworking', 'farmersdelight:chests/fd_village_plains_house', 35],
  ['woodworking', 'minecraft:chests/abandoned_mineshaft', 35],
]

// --- INJECT INTO LOOT TABLES ---
ServerEvents.genericLootTables(function(event) {
  for (var i = 0; i < SCROLL_SOURCES.length; i++) {
    var stageId   = SCROLL_SOURCES[i][0]
    var lootTable = SCROLL_SOURCES[i][1]
    var pct       = SCROLL_SOURCES[i][2]
    var scrollItem = Item.of('historystages:research_scroll').withNBT({StageResearch: stageId})
    ;(function(table, item, weight) {
      event.modify(table, function(loot) {
        loot.addPool(function(pool) {
          pool.rolls = 1
          pool.addItem(item, weight)
          pool.addEmpty(100 - weight)
        })
      })
    })(lootTable, scrollItem, pct)
  }
  console.info('[Sinborn V7] rarity-rebuilt ' + SCROLL_SOURCES.length + ' scroll entries (tier=chapter)')
})
